// Copyright (C) 2024 OpenTier FZCO
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

export global ConnectivityStatusAdapter {
    in property <bool> isConnected: true;
}

export component ConnectivityStatus {
    in property <bool> isConnected <=> ConnectivityStatusAdapter.isConnected;
    height: 20px;
    width: 20px;
    Image {
        source: (isConnected ? @image-url("assets/status_bar/signal_green.svg") : @image-url("assets/status_bar/signal_red.svg"));
    }
}
