// Copyright (C) 2024 OpenTier FZCO
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import { Theme } from "../theme.slint";

export global CourrierNotificationsAdpater {
    in property <string> message: "";
}

export component CourrierNotifications inherits Window {
    in property <string> message: CourrierNotificationsAdpater.message;

    width: 250px;
    height: 350px;

    Image {
        source: @image-url("assets/card.svg");
        height: 100%;
        width: 100%;
    }

    Image {
        source: @image-url("assets/left_widget/notifications.svg");
        x: parent.width - 100px;
        y: 50px;
        width: 40px;
        height: 40px;
    }

    VerticalLayout {
        alignment: center;
        padding: 50px;
        spacing: 10px;

        Text {
            text: message;
            wrap: word-wrap;
            letter-spacing: 1px;
            font-size: 15px;
            color: Theme.ot-white;
        }
    }
}
