// Copyright (C) 2024 OpenTier FZCO
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import "components/assets/fonts/Orbitron-Regular.ttf";

export global Theme {
    // primary
    out property <color> ot-dark-green: #002D2A;
    out property <color> ot-light-green: #22BC72;
    out property <color> ot-purple: #C1B7ED;
    out property <color> ot-gray: #D4D4D4;
    out property <color> ot-dark-gray: #2B2B2B;
    out property <color> ot-white:#F5F5F5;
    out property <color> black: #000000;

    out property <color> ot-light-green-alpha-50: rgba(34, 188, 114, 0.5);

    out property <string> font-family: "Orbitron";
}
